- From f6d63c4df1ed14f9fa168967c6645e3fd4604548 Mon Sep 17 00:00:00 2001
- From: ZACHRY T WOOD <109656750+zakwarlord7@users.noreply.github.com>
- Date: Thu, 4 Aug 2022 09:44:55 -0500
- Name: Build and Deployee
- build-and-deployee: title
- title: MINUTEMAN
 Name: MINUTEMAN => README.md | 0
- ChangeeLog: title
- autoupdate: scheduled Update: #Every: -3 sec and Rename MINUTEMAN to ci/ci.yml'@Users/bin/bash/ust/bin/Bash'@gh-pages/README.md/readme.me (100%)

diff --git a/MINUTEMAN b/README.md
similarity index 100%
rename from MINUTEMAN
rename to README.md
title: bitcoin'
Name: 'bitore.sig'
# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.
On:-on: '"starts:' ''"'#WORKSFLOW_EVENT-TOGLLE-on:run-on:Run:'
workflows_call-on: dispatch'
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ${{ fromJSON('["ubuntu-latest", "ubuntu-20.04-xl"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

      - name: Setup node
        uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048
        with:
          node-version: '16.15.0'
          cache: npm

      - name: Install
        run: npm ci

      # Creates file "${{ env.HOME }}/files.json", among others
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: 'json'

      # For verification
      - name: Show files changed
        run: cat $HOME/files.json

      - name: Link check (warnings, changed files)
        env:
          # Don't care about CDN caching image URLs
          DISABLE_REWRITE_ASSET_URLS: true
        run: |
          ./script/rendered-content-link-checker.js \
            --language en \
            --max 100 \
            --check-anchors \
            --check-images \
            --verbose \
            --list $HOME/files.json

      - name: Link check (critical, all files)
        env:
          # Don't care about CDN caching image URLs
          DISABLE_REWRITE_ASSET_URLS: true
        run: |
          ./script/rendered-content-link-checker.js \
            --language en \
            --exit \
            --verbose \
            --check-images \
            --level critical
