name: 60 Days Stale Check

# **What it does**: Pull requests older than 60 days will be flagged as stale.
# **Why we have it**: We want to manage our queue of issues and pull requests.
# **Who does it impact**: Everyone that works on docs or docs-internal.

on:
  schedule:
    - cron: '40 16 * * *' # Run each day at 16:40 UTC / 8:40 PST

jobs:
  stale:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@9d6f46564a515a9ea11e7762ab3957ee58ca50da
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity.'
          days-before-stale: 60
          days-before-close: -1
          only-labels: 'engineering,Triaged,Improve existing docs,Core,Ecosystem'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'never-stale'
          exempt-issue-labels: 'never-stale'
          
Skip to content
Pull requests
Issues
Codespaces
Marketplace
Explore
@mowjoejoejoejoe
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
github /
docs
Public

Fork your own copy of github/docs

Code
Issues 93
Pull requests 65
Discussions
Actions
Projects 4
Security

    Insights

Repo Sync Stalls
Repo Sync Stalls #9820

    Jobs

    Run details

repo-sync-stalls
succeeded Mar 5, 2023 in 3s
2s
Current runner version: '2.302.1'
Operating System
  Ubuntu
  22.04.2
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230227.2
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230227.2/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230227.2
Runner Image Provisioner
  2.0.117.1
GITHUB_TOKEN Permissions
  Metadata: read
  PullRequests: read
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/github-script@98814c53be79b1d30f795b907e553d8679345975' (SHA:98814c53be79b1d30f795b907e553d8679345975)
Download action repository 'someimportantcompany/github-actions-slack-message@1d367080235edfa53df415bd8e0bbab480f29bad' (SHA:1d367080235edfa53df415bd8e0bbab480f29bad)
Complete job name: repo-sync-stalls
0s
0s
0s
:Build::
Publish :
