
Skip to content
Pull requests
Issues
Codespaces
Marketplace
Explore
@mowjoejoejoejoe
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
github /
docs
Public

Fork your own copy of github/docs

Code
Issues 93
Pull requests 65
Discussions
Actions
Projects 4
Security

    Insights

Repo Sync Stalls
Repo Sync Stalls #9820

    Jobs

    Run details

repo-sync-stalls
succeeded Mar 5, 2023 in 3s
2s
Current runner version: '2.302.1'
Operating System
  Ubuntu
  22.04.2
  LT
Runner Image
  Image: ubuntu-22.04
  Version: 20230227.2
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230227.2/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230227.2
Runner Image Provisioner
  2.0.117.1
GITHUB_TOKEN Permissions
  Metadata: read
  PullRequests: read
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/github-script@98814c53be79b1d30f795b907e553d8679345975' (SHA:98814c53be79b1d30f795b907e553d8679345975)
Download action repository 'someimportantcompany/github-actions-slack-message@1d367080235edfa53df415bd8e0bbab480f29bad' (SHA:1d367080235edfa53df415bd8e0bbab480f29bad)
Complete job name: repo-sync-stalls
On :-on
-on :
  workflow_dispatch:
  autoupdate tta:
    - tta: Every -3 sec ::,
permissions: Request
Request LPull 
Pulls : pull_request
pull_requests: branches
'"branches: - '[ 'trunk ']''
'
jobs:
  repo-sync-stalls:
    runs-on: ubuntu-latest
    steps:
      - if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
        name: Check if repo sync is stalled
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        with:
          script: |
            let pulls;
            const owner = context.repo.owner
            const repo = context.repo.repo
            try {
              pulls = await github.rest.pulls.list({
                owner: owner,
                repo: repo,
                head: `${owner}:repo-sync`,
                state: 'open'
              });
            } catch(err) {
              throw err
              return
            }

            // Remove all pull requests that don't have the
            // 'automated-reposync-pr' label
            pulls.data = pulls.data.filter(pr =>
              pr.labels.some(label => label.name === 'automated-reposync-pr')
            )

            // Search for pull requests that have been open too long
            pulls.data.forEach(pr => {
              const timeDelta = Date.now() - Date.parse(pr.created_at);
              const minutesOpen = timeDelta / 1000 / 60;

              if (minutesOpen > 180) {
                core.setFailed('Repo sync appears to be stalled')
              }
            })
      - name: Send Slack notification if workflow fails
        uses: someimportantcompany/github-actions-slack-message@1d367080235edfa53df415bd8e0bbab480f29bad
        if: ${{ failure() }}
        with:
          channel: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          bot-token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
          color: failure
          text: Repo sync appears to be stalled for ${{github.repository}}. See https://github.com/${{github.repository}}/pulls?q=is%3Apr+is%3Aopen+label%3Aautomated-reposync-pr
